# 15_Comp_A_Hemant Chaubey

# Exception Handling

In [1]:
marks = 99
try:
    a = marks / 0
except ZeroDivisionError:
    print("Cannot divide by 0")
    print("Dividing by 1")
    a = marks / 1
print(a)

Cannot divide by 0
Dividing by 1
99.0


In [2]:
try:
   age = int(input("Age: "))
   income = 20000
   risk = income / age
   print(age)
   print(risk)
except ZeroDivisionError:
   print("Age cannot be 0")
except ValueError:
   print("Invalid Value")

Age: 0
Age cannot be 0


In [3]:
try:
   age = int(input("Age: "))
except ZeroDivisionError:
   print("Age cannot be 0")
except ValueError:
   print("Invalid Value")

Age: 19
19
1052.6315789473683


In [4]:
try:
   age = int(input("Age: "))
   income = 20000
   risk = income / age
   print(age)
   print(risk)
except ZeroDivisionError:
   print("Age cannot be 0")
except ValueError:
   print("Invalid Value")

Age: hemant
Invalid Value


In [5]:
try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")

Variable x is not defined


In [6]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

Hello
Nothing went wrong


In [7]:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


In [8]:
list = ["apple", "banana", "cherry"]

try:
    print(list[0])
    print(list[2])
    print(list[8])
    
except:
    print("Index error ocurred")
    
finally:
    print("Finally block executed successfully")
    


apple
cherry
Index error ocurred
Finally block executed successfully


In [9]:
try:
    f = open("ab.txt")
    
except:
    print("File not found... Please Check")

File not found... Please Check


# File Handling

In [10]:
from pathlib import Path

In [11]:
import os

In [12]:
path = Path()
print(path)

.


In [13]:
f = open("hemant.txt", "rt")
print(f)

<_io.TextIOWrapper name='hemant.txt' mode='rt' encoding='cp1252'>


In [14]:
f = open("hemant.txt", "rt")
print(f.read())

Hey there...
Hemant here


In [15]:
f = open("demofile1.txt", "a")
f.close()

In [16]:
f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

In [17]:
f = open("demofile2.txt", "r")
print(f.read())

Now the file has more content!


In [18]:
f = open("demofile3.txt", "w")
f.write("Another demo file")
f.close()

In [19]:
f = open("demofile3.txt", "r")
print(f.read())

Another demo file


In [20]:
if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")

The file does not exist


In [21]:
if os.path.exists("demofile2.txt"):
  os.remove("demofile2.txt")
else:
  print("The file does not exist")

# Python Regex

In [22]:
import re

In [23]:
txt = "hello hemant"
x = re.findall("h", txt)
print(x)

['h', 'h']


In [24]:
txt = "hello hemant"

x = re.findall("nandani", txt)
print(x)

if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

[]
No match


In [25]:
txt = "hello nandani"
x = re.search("\s", txt)

print("The first white-space character is located in position:", x.start()) 

The first white-space character is located in position: 5


In [26]:
txt = "hello nandani"
x = re.search("Portugal", txt)
print(x)

None


In [27]:
str = "The Ramayana is an ancient Sanskrit epic about Rama and Sita. It is one of the two most important ancient epics of India, the first one being the ancient Mahabharata. The epic was originally written by sage (rishi) Valmiki of Ancient India. The book has about 24,000 verses and is divided into seven parts."

In [28]:
x = re.search("sage", str)
print(x)

<re.Match object; span=(202, 206), match='sage'>


In [29]:
x = re.search("\s", str)
print("The first white-space character is located in position:", x.start()) 

The first white-space character is located in position: 3


In [30]:
x = re.split("\s", str)
print(x)

['The', 'Ramayana', 'is', 'an', 'ancient', 'Sanskrit', 'epic', 'about', 'Rama', 'and', 'Sita.', 'It', 'is', 'one', 'of', 'the', 'two', 'most', 'important', 'ancient', 'epics', 'of', 'India,', 'the', 'first', 'one', 'being', 'the', 'ancient', 'Mahabharata.', 'The', 'epic', 'was', 'originally', 'written', 'by', 'sage', '(rishi)', 'Valmiki', 'of', 'Ancient', 'India.', 'The', 'book', 'has', 'about', '24,000', 'verses', 'and', 'is', 'divided', 'into', 'seven', 'parts.']


In [31]:
x = re.split("\s", str, 5)
print(x)

['The', 'Ramayana', 'is', 'an', 'ancient', 'Sanskrit epic about Rama and Sita. It is one of the two most important ancient epics of India, the first one being the ancient Mahabharata. The epic was originally written by sage (rishi) Valmiki of Ancient India. The book has about 24,000 verses and is divided into seven parts.']


In [32]:
x = re.sub("\s", " * ", str)
print(x)

The * Ramayana * is * an * ancient * Sanskrit * epic * about * Rama * and * Sita. * It * is * one * of * the * two * most * important * ancient * epics * of * India, * the * first * one * being * the * ancient * Mahabharata. * The * epic * was * originally * written * by * sage * (rishi) * Valmiki * of * Ancient * India. * The * book * has * about * 24,000 * verses * and * is * divided * into * seven * parts.


In [33]:
x = re.sub("\s", " # ", str, 2)
print(x)

The # Ramayana # is an ancient Sanskrit epic about Rama and Sita. It is one of the two most important ancient epics of India, the first one being the ancient Mahabharata. The epic was originally written by sage (rishi) Valmiki of Ancient India. The book has about 24,000 verses and is divided into seven parts.


In [34]:
x = re.search("Ram", str)
print(x)

<re.Match object; span=(4, 7), match='Ram'>


In [35]:
x = re.search(r"\bS\w+", str)
print(x.span())

(27, 35)


In [36]:
x = re.search(r"\bR\w+", str)
print(x.span())

(4, 12)


# List

In [37]:
print(list)

['apple', 'banana', 'cherry']


In [38]:
print(len(list))

3


In [39]:
type(list)

list

In [40]:
list[0]

'apple'

In [41]:
list[0:2]

['apple', 'banana']

In [42]:
list[-1]

'cherry'

In [43]:
list[0:-1]

['apple', 'banana']

In [44]:
list[1] = "mango"

In [45]:
list[1]

'mango'

In [46]:
list.append('banana')

In [47]:
list

['apple', 'mango', 'cherry', 'banana']

In [48]:
list.pop()

'banana'

In [49]:
list.insert(1, "pear")
print(list)

['apple', 'pear', 'mango', 'cherry']


In [50]:
list2 = ["pineapple", "papaya"]
list.extend(list2)
print(list)

['apple', 'pear', 'mango', 'cherry', 'pineapple', 'papaya']


In [51]:
list.remove("pear")
print(list)

['apple', 'mango', 'cherry', 'pineapple', 'papaya']


In [52]:
for i in list:
    print(i)

apple
mango
cherry
pineapple
papaya


In [53]:
list.sort()
print(list)

['apple', 'cherry', 'mango', 'papaya', 'pineapple']


# Tuples

In [54]:
tuple = ("apple", "banana", "cherry")

In [55]:
print(tuple)

('apple', 'banana', 'cherry')


In [56]:
print(len(tuple))

3


In [57]:
type(tuple)

tuple

In [58]:
tuple[1]

'banana'

In [59]:
tuple[-1]

'cherry'

In [60]:
tuple[0:-1]

('apple', 'banana')

In [61]:
for i in tuple:
    print(i)

apple
banana
cherry


# NumPy

In [62]:
import numpy as np

In [63]:
arr1 = np.array([1, 2, 3, 4, 5])

In [64]:
print(arr1)

[1 2 3 4 5]


In [65]:
print(type(arr1))

<class 'numpy.ndarray'>


In [66]:
print(arr1.ndim)

1


In [67]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [68]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
print(arr2.ndim)

2


In [70]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [71]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [72]:
print(arr3.ndim)

3


In [73]:
print(arr1[2])

3


In [74]:
print(arr3[1][1][2])

6


In [75]:
arr1[0:2]

array([1, 2])

In [76]:
np.random.seed(0)
x1 = np.random.randint(10, size = 5)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))
print("One Dimension", x1)
print("\n")
print("Two Dimension", x2)
print("\n")
print("Three Dimension", x3)

One Dimension [5 0 3 3 7]


Two Dimension [[9 3 5 2]
 [4 7 6 8]
 [8 1 6 7]]


Three Dimension [[[7 8 1 5 9]
  [8 9 4 3 0]
  [3 5 0 2 3]
  [8 1 3 3 3]]

 [[7 0 1 9 9]
  [0 4 7 3 2]
  [7 2 0 0 4]
  [5 5 6 8 4]]

 [[1 4 9 8 1]
  [1 7 9 9 3]
  [6 7 2 0 3]
  [5 9 4 4 6]]]


In [77]:
x2[2,0]

8

In [78]:
x2[2,-1]

7

In [79]:
x2[::-1,:]

array([[8, 1, 6, 7],
       [4, 7, 6, 8],
       [9, 3, 5, 2]])

In [80]:
x2[::-1,::-1]

array([[7, 6, 1, 8],
       [8, 6, 7, 4],
       [2, 5, 3, 9]])

In [81]:
x3

array([[[7, 8, 1, 5, 9],
        [8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3],
        [8, 1, 3, 3, 3]],

       [[7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4],
        [5, 5, 6, 8, 4]],

       [[1, 4, 9, 8, 1],
        [1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3],
        [5, 9, 4, 4, 6]]])

In [82]:
x3[1,1:3:, 1:4:2]

array([[4, 3],
       [2, 0]])

In [83]:
arr=np.linspace(0,15,16)

In [84]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [85]:
arr=np.linspace(0,15,20)
arr

array([ 0.        ,  0.78947368,  1.57894737,  2.36842105,  3.15789474,
        3.94736842,  4.73684211,  5.52631579,  6.31578947,  7.10526316,
        7.89473684,  8.68421053,  9.47368421, 10.26315789, 11.05263158,
       11.84210526, 12.63157895, 13.42105263, 14.21052632, 15.        ])

In [86]:
arr=np.linspace(0,15)
arr

array([ 0.        ,  0.30612245,  0.6122449 ,  0.91836735,  1.2244898 ,
        1.53061224,  1.83673469,  2.14285714,  2.44897959,  2.75510204,
        3.06122449,  3.36734694,  3.67346939,  3.97959184,  4.28571429,
        4.59183673,  4.89795918,  5.20408163,  5.51020408,  5.81632653,
        6.12244898,  6.42857143,  6.73469388,  7.04081633,  7.34693878,
        7.65306122,  7.95918367,  8.26530612,  8.57142857,  8.87755102,
        9.18367347,  9.48979592,  9.79591837, 10.10204082, 10.40816327,
       10.71428571, 11.02040816, 11.32653061, 11.63265306, 11.93877551,
       12.24489796, 12.55102041, 12.85714286, 13.16326531, 13.46938776,
       13.7755102 , 14.08163265, 14.3877551 , 14.69387755, 15.        ])

In [87]:
arr= np.arange(1,15,2)

In [88]:
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [89]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [90]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

# Pandas

In [91]:
import pandas as pd

In [92]:
l = [33,66,99,12]
pd.Series(l)

0    33
1    66
2    99
3    12
dtype: int64

In [93]:
pd.Series(l, index =['i','ii','iii','iv'])

i      33
ii     66
iii    99
iv     12
dtype: int64

In [94]:
d={'name':['Hemant','Ram','Shyam'], 'percentage':[90,86,65], 'branch':['cs', 'it', 'civil']}

In [95]:
d

{'name': ['A', 'B', 'C'],
 'percentage': [90, 86, 65],
 'branch': ['cs', 'it', 'civil']}

In [96]:
pd.DataFrame(d)

name  percentage branch
0    A          90     cs
1    B          86     it
2    C          65  civil